spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo?currentSchema=s_todo
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: s_todo
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookshareapp598@gmail.com
    password: njveflemejirtejk
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true